### ISSUE TITLE
checkpoint 1, ready for review

### ISSUE THREAD

**Issue by Rashad-636** [Rashad-636/sportsPerformancePredictor#1]
Very rough draft for my screens!

@pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
Hi @Rashad-636!

First, I'm so glad that you found inspiration by exploring the myriad of apis that are out there! This seems like it'll be a fund project for you to work on and I'm looking forward to seeing the first iteration!

**Problem statement** 

Does a good job explaining the solution; I think it would be helpful to give background on other websites/applications and what's not great about them as predictors - more clearly answer: what problem does your solution solve? 

- [x] If you know which services/AI providers you'll be using, it would be nice to list those in the readme. If you don't know yet, it's ok to add those details later. If "later" is the case, make a note to do so.

**User stories w/ MVP stories identified** Your users stories are clear and well-written following the best practices for user stories. They clearly communicate what your application will do, and the UI/UX aspect seems to be well-thought-out. Your MVP stories appear to include what's needed for the ent java project requirements like crud, and multiple tables with more than one one-to-many relationship. I think you've done a good job scoping the project to what's doable this semester.

- [x] Which of the UI/UX stories are MVP? It seems like at least some should be? All?

**Wireframes**. Good work on these! The wireframes clearly communicate what each page will do. I appreciate the hand-drawn style!

- [x] There's a story for adding notes, but I don't think I saw this in the wireframes.

- [x] Something to know is that we'll be using AWS cognito for sign up/sign in capability, so there are some screens that you may not have to worry about as they can be provided by Cognito itself.  We'll learn more about this in week 7.

**Project Plan** A good start!

- [ ] I recommend at least identifying which user story you plan to work on each week.  Chatgpt can be helpful brainstorming tasks if you are having trouble coming up with them. I think the more detailed you can be the better. What do you think about creating a task for each story to decide which jsp/s, controllers, entities, tables you'll need for that story.  Revising the plan could be a task on the plan itself (woah!)

**Reflection/Time log** Keep up the good work with this. Document all time spent in class, not just time on your indie project. This helps us both evaluate what might need more or less time!


**********
**To reach "met" status for checkpoint 1:**

Complete the items listed for Problem Statement (if you know the services/ai), Stories and Project Plan, the respond to this issue and I'll review.  If you have any questions, please ask!

**Comment by Rashad-636** [comment]
Everything under signup, sign in, and Account management are MVP and the user stories that have view, create and delete capitalized.

Changes made on the README and project plan as well

@pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
Updates look good @Rashad-636.

You may want to include in the plan a step to implement the generic DAO. Then as you add each entity, they will be unit tested similar to the unit testing we did in weeks 4 and 5.
